### ISSUE TITLE
how to access private?

### ISSUE THREAD

**Issue by very3b** [idea-fasoc/fasoc#7]
May I access private/cad?

**Comment by tajayi** [comment]
Unfortunately we cannot grant access to the private/ directory because it contains
1) Proprietary EDA Tool information (e.g. scripts, commands, etc)
2) Protected/NDA information about the PDK and standard cells used. 

We are working to carve out a portion of what's in there that can be run on opensource tools in combination with opensource PDKs/Kits.

Thanks for you interest
